# Generated by Django 6.1 on 2026-08-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='reel_1_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Reel 1: Постер (обложка)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reel_2_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Reel 2: Постер (обложка)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reel_3_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Reel 3: Постер (обложка)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reel_4_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Reel 4: Постер (обложка)'),
        ),
    ]
