# Generated by Django 6.1 on 2026-08-20 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_reel_1_poster_homepage_reel_2_poster_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='giftcards_picker_note',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='giftcards_picker_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='loyalty_stamp_prompt',
        ),
        migrations.AddField(
            model_name='homepage',
            name='announcement_ticker_ka',
            field=models.TextField(blank=True, default='წერტილი • თქვენი სივრცე სუნთქვისთვის • 30% ფასდაკლება მე-5 მასაჟზე • ბათუმი, ლუკა ასათიანის 46', verbose_name='Бегущая строка (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='announcement_ticker_ru',
            field=models.TextField(blank=True, default='ТОЧКА • ВАШЕ ПРОСТРАНСТВО ДЛЯ ДЫХАНИЯ • СКИДКА 30% НА 5-Й СЕАНС • БАТУМИ, УЛ. ЛУКИ АСАТИАНИ, 46', verbose_name='Бегущая строка (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='booking_btn_text_ka',
            field=models.CharField(blank=True, default='ჯავშნის დადასტურება', max_length=50, verbose_name='Бронирование: Кнопка (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='booking_btn_text_ru',
            field=models.CharField(blank=True, default='ПОДТВЕРДИТЬ ЗАПИСЬ', max_length=50, verbose_name='Бронирование: Кнопка (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='booking_heading_ka',
            field=models.CharField(blank=True, default='სეანსის დაჯავშნა', max_length=100, verbose_name='Бронирование: Заголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='booking_heading_ru',
            field=models.CharField(blank=True, default='ЗАБРОНИРОВАТЬ СЕАНС', max_length=100, verbose_name='Бронирование: Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='booking_lead_ka',
            field=models.TextField(blank=True, default='აირჩიეთ სასურველი რიტუალი და დრო. მასტერი ანა კოლოსოვა დაადასტურებს თქვენს ჯავშანს 15 წუთში.', verbose_name='Бронирование: Описание (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='booking_lead_ru',
            field=models.TextField(blank=True, default='Выберите желаемый ритуал и удобное время. Мастер Анна Колосова подтвердит вашу бронь в течение 15 минут.', verbose_name='Бронирование: Описание (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='btn_book_header_text_ka',
            field=models.CharField(blank=True, default='დაჯავშნა', max_length=50, verbose_name='Кнопка в шапке (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='btn_book_header_text_ru',
            field=models.CharField(blank=True, default='ЗАБРОНИРОВАТЬ', max_length=50, verbose_name='Кнопка в шапке (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_author_ka',
            field=models.CharField(blank=True, default='— ანა კოლოსოვა • დამფუძნებელი და თერაპევტი', max_length=100, verbose_name='01 Автор цитаты (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_author_ru',
            field=models.CharField(blank=True, default='— Анна Колосова • Основатель и мастер студии ТОЧКА', max_length=100, verbose_name='01 Автор цитаты (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_card_1_text_ka',
            field=models.TextField(blank=True, default='საავტორო უწყვეტი კონტაქტის ტექნიკა: თერაპევტის ხელები პრაქტიკულად არ შორდება სხეულს, მოძრაობს მდორე მედიტაციურ ნაკადში.', verbose_name='01 Карточка 1 Текст (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_card_1_text_ru',
            field=models.TextField(blank=True, default='Авторская техника непрерывного контакта: руки мастера практически не отрываются от тела, переходя из одного движения в другое. Такой ритм дает нервной системе сигнал безопасности и глубоко снимает накопившийся стресс.', verbose_name='01 Карточка 1 Текст (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_card_1_title_ka',
            field=models.CharField(blank=True, default='უწყვეტი კონტაქტი', max_length=100, verbose_name='01 Карточка 1 Заголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_card_1_title_ru',
            field=models.CharField(blank=True, default='Непрерывный контакт', max_length=100, verbose_name='01 Карточка 1 Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_card_2_text_ka',
            field=models.TextField(blank=True, default='ნატურალური ქოქოსის ზეთი, რბილი პირსახოცები, პერსონალური მუსიკა და ყავა ან ჩაი სეანსის შემდეგ.', verbose_name='01 Карточка 2 Текст (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_card_2_text_ru',
            field=models.TextField(blank=True, default='Натуральное кокосовое масло или нежный питательный крем, белоснежные полотенца, персональный плейлист гостя вместо шаблонных звуков и чашка чая или кофе после сеанса.', verbose_name='01 Карточка 2 Текст (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_card_2_title_ka',
            field=models.CharField(blank=True, default='მზრუნველობის ატმოსფერო', max_length=100, verbose_name='01 Карточка 2 Заголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_card_2_title_ru',
            field=models.CharField(blank=True, default='Атмосфера искренней заботы', max_length=100, verbose_name='01 Карточка 2 Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_heading_ka',
            field=models.CharField(blank=True, default='კონცეფცია და ფილოსოფია', max_length=100, verbose_name='01 Заголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_heading_ru',
            field=models.CharField(blank=True, default='КОНЦЕПЦИЯ И ФИЛОСОФИЯ', max_length=100, verbose_name='01 Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_quote_ka',
            field=models.TextField(blank=True, default='„წერტილი ჟღერს თავდაჯერებულად და სუფთად, როგორც ღრმა ჩასუნთქვა და ნელი ამოსუნთქვა. ხაზების სიმკაცრე ქმნის სტაბილურობისა და საყრდენის შეგრძნებას“.', verbose_name='01 Цитата (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='concept_quote_ru',
            field=models.TextField(blank=True, default='«ТОЧКА звучит уверенно и чисто, как глубокий вдох и медленный выдох. Строгость линий создает ощущение стабильности и опоры — фундамент, на котором строится восстановление».', verbose_name='01 Цитата (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_motto_ka',
            field=models.TextField(blank=True, default='თქვენი სივრცე სუნთქვისთვის. ესთეტიკა და კომფორტი, როგორც განკურნების ნაწილი.', verbose_name='Подвал: Слоган (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_motto_ru',
            field=models.TextField(blank=True, default='Ваше пространство для дыхания. Эстетика и забота как часть процесса восстановления.', verbose_name='Подвал: Слоган (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='giftcards_btn_text_ka',
            field=models.CharField(blank=True, default='სერტიფიკატის შეძენა', max_length=50, verbose_name='04 Кнопка (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='giftcards_btn_text_ru',
            field=models.CharField(blank=True, default='ОФОРМИТЬ СЕРТИФИКАТ', max_length=50, verbose_name='04 Кнопка (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='giftcards_heading_ka',
            field=models.CharField(blank=True, default='სასაჩუქრე სერტიფიკატები', max_length=100, verbose_name='04 Заголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='giftcards_heading_ru',
            field=models.CharField(blank=True, default='ПОДАРОЧНЫЕ СЕРТИФИКАТЫ', max_length=100, verbose_name='04 Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='giftcards_subtext_ka',
            field=models.TextField(blank=True, default='აჩუქეთ სიმშვიდის, დასვენებისა და ზრუნვის დაუვიწყარი წუთები.', verbose_name='04 Подзаголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='giftcards_subtext_ru',
            field=models.TextField(blank=True, default='Подарите близким моменты спокойствия, тишины и бережного восстановления.', verbose_name='04 Подзаголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_badge_tag_ka',
            field=models.CharField(blank=True, default='სანქტუარი სივრცე', max_length=100, verbose_name='Hero: Бейдж (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_badge_tag_ru',
            field=models.CharField(blank=True, default='SANCTUARY ПРОСТРАНСТВО', max_length=100, verbose_name='Hero: Бейдж (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn_book_text_ka',
            field=models.CharField(blank=True, default='სეანსის დაჯავშნა', max_length=50, verbose_name='Hero: Кнопка 2 (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn_book_text_ru',
            field=models.CharField(blank=True, default='ЗАПИСАТЬСЯ НА СЕАНС', max_length=50, verbose_name='Hero: Кнопка 2 (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn_explore_text_ka',
            field=models.CharField(blank=True, default='რიტუალების ნახვა', max_length=50, verbose_name='Hero: Кнопка 1 (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn_explore_text_ru',
            field=models.CharField(blank=True, default='ВЫБРАТЬ РИТУАЛ', max_length=50, verbose_name='Hero: Кнопка 1 (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_card_tag_title_ka',
            field=models.CharField(blank=True, default='წერტილის რიტუალი', max_length=100, verbose_name='Hero: Метка на фото (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_card_tag_title_ru',
            field=models.CharField(blank=True, default='РИТУАЛ ТОЧКА', max_length=100, verbose_name='Hero: Метка на фото (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description_ka',
            field=models.TextField(blank=True, default='წერტილი იბადება სხეულისა და სულის შეხვედრის ადგილზე — სადაც შეხება ხდება ზრუნვის ენა, ხოლო თავად სივრცე სიმშვიდით სუნთქავს.', verbose_name='Hero: Описание (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description_ru',
            field=models.TextField(blank=True, default='ТОЧКА рождается на стыке тела и души — там, где прикосновение становится языком заботы, а само пространство дышит спокойствием. Это место, где можно оставить за порогом шум города и снова услышать себя.', verbose_name='Hero: Описание (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_feat_1_text_ka',
            field=models.CharField(blank=True, default='უწყვეტი კონტაქტის ტექნიკა', max_length=100, verbose_name='Hero: Преимущество 1 (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_feat_1_text_ru',
            field=models.CharField(blank=True, default='Техника непрерывного контакта', max_length=100, verbose_name='Hero: Преимущество 1 (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_feat_2_text_ka',
            field=models.CharField(blank=True, default='ნატურალური ქოქოსის ზეთი', max_length=100, verbose_name='Hero: Преимущество 2 (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_feat_2_text_ru',
            field=models.CharField(blank=True, default='Натуральное кокосовое масло', max_length=100, verbose_name='Hero: Преимущество 2 (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_feat_3_text_ka',
            field=models.CharField(blank=True, default='10% ფასდაკლება 1-ლ სეანსზე • 30% მე-5-ზე', max_length=100, verbose_name='Hero: Преимущество 3 (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_feat_3_text_ru',
            field=models.CharField(blank=True, default='Скидка 10% на 1-й сеанс • 30% на 5-й', max_length=100, verbose_name='Hero: Преимущество 3 (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_main_title_ka',
            field=models.CharField(blank=True, default='თქვენი სივრცე სუნთქვისთვის.', max_length=200, verbose_name='Hero: Заголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_main_title_ru',
            field=models.CharField(blank=True, default='Ваше пространство для дыхания.', max_length=200, verbose_name='Hero: Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='loyalty_desc_ka',
            field=models.TextField(blank=True, default='მეტი სიამოვნება და ზრუნვა საკუთარ თავზე. 30%-იანი ფასდაკლება მე-5 მასაჟზე — ჩვენი მადლიერების რიტუალი.', verbose_name='03 Описание (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='loyalty_desc_ru',
            field=models.TextField(blank=True, default='Больше удовольствия и заботы о себе. Скидка 30% на каждый 5-й массаж — наш маленький ритуал благодарности за ваше доверие.', verbose_name='03 Описание (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='loyalty_heading_ka',
            field=models.CharField(blank=True, default='მადლიერების რიტუალი', max_length=100, verbose_name='03 Заголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='loyalty_heading_ru',
            field=models.CharField(blank=True, default='РИТУАЛ БЛАГОДАРНОСТИ', max_length=100, verbose_name='03 Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='loyalty_subtitle_ka',
            field=models.CharField(blank=True, default='30% ფასდაკლება ყოველ მე-5 მასაჟზე', max_length=150, verbose_name='03 Подзаголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='loyalty_subtitle_ru',
            field=models.CharField(blank=True, default='Привилегия 30% на каждый 5-й массаж', max_length=150, verbose_name='03 Подзаголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='manifesto_huge_text_ka',
            field=models.CharField(blank=True, default='ALL YOU KNEAD IS CARE', max_length=100, verbose_name='Манифест: Большой текст (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='manifesto_huge_text_ru',
            field=models.CharField(blank=True, default='ALL YOU KNEAD IS CARE', max_length=100, verbose_name='Манифест: Большой текст (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='palette_heading_ka',
            field=models.CharField(blank=True, default='ფერების პალიტრა და იდენტობა', max_length=100, verbose_name='Палитра: Заголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='palette_heading_ru',
            field=models.CharField(blank=True, default='ЦВЕТОВАЯ ПАЛИТРА И АЙДЕНТИКА', max_length=100, verbose_name='Палитра: Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_badge_ka',
            field=models.CharField(blank=True, default='პირველი ვიზიტი', max_length=50, verbose_name='02 Промо: Бейдж (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_badge_ru',
            field=models.CharField(blank=True, default='ПЕРВЫЙ ВИЗИТ', max_length=50, verbose_name='02 Промо: Бейдж (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_btn_text_ka',
            field=models.CharField(blank=True, default='10%-იანი ფასდაკლების მიღება', max_length=50, verbose_name='02 Промо: Кнопка (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_btn_text_ru',
            field=models.CharField(blank=True, default='ПОЛУЧИТЬ СКИДКУ 10%', max_length=50, verbose_name='02 Промо: Кнопка (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_subtitle_ka',
            field=models.TextField(blank=True, default='გაეცანით ჩვენს საავტორო უწყვეტი კონტაქტის მასაჟს. მოიცავს ორგანულ ქოქოსის ზეთს და ჩაის/ყავას სეანსის შემდეგ.', verbose_name='02 Промо: Описание (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_subtitle_ru',
            field=models.TextField(blank=True, default='Познакомьтесь с авторской техникой непрерывного контакта и ощутите глубокое расслабление. Натуральные масла и чай/кофе включены.', verbose_name='02 Промо: Описание (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_title_ka',
            field=models.CharField(blank=True, default='10% ფასდაკლება პირველ ვიზიტზე', max_length=150, verbose_name='02 Промо: Заголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo_title_ru',
            field=models.CharField(blank=True, default='Привилегия 10% на первый визит', max_length=150, verbose_name='02 Промо: Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reels_heading_ka',
            field=models.CharField(blank=True, default='ატმოსფერო და ვიდეოები', max_length=100, verbose_name='05 Заголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reels_heading_ru',
            field=models.CharField(blank=True, default='АТМОСФЕРА И REELS', max_length=100, verbose_name='05 Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reels_subtext_ka',
            field=models.CharField(blank=True, default='ღრმა სუნთქვის, თბილი ზეთებისა და მზრუნველი შეხების წუთები @toch._ka', max_length=200, verbose_name='05 Подзаголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reels_subtext_ru',
            field=models.CharField(blank=True, default='Моменты глубокого дыхания, теплых масел и тактильной заботы в @toch._ka', max_length=200, verbose_name='05 Подзаголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rituals_heading_ka',
            field=models.CharField(blank=True, default='თერაპიები და რიტუალები', max_length=100, verbose_name='02 Заголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rituals_heading_ru',
            field=models.CharField(blank=True, default='ТЕРАПИИ И РИТУАЛЫ', max_length=100, verbose_name='02 Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rituals_subtext_ka',
            field=models.TextField(blank=True, default='ავთენტური პროცედურები, ზუსტი მიოფასციალური ტექნიკა და ღრმა აღდგენითი ზრუნვა ბათუმში.', verbose_name='02 Подзаголовок (GE)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rituals_subtext_ru',
            field=models.TextField(blank=True, default='Проверенные методики, прицельная проработка триггерных зон и холистический уход в Батуми.', verbose_name='02 Подзаголовок (RU)'),
        ),
        migrations.AddField(
            model_name='ritual',
            name='description_ka',
            field=models.TextField(blank=True, verbose_name='Описание (GE)'),
        ),
        migrations.AddField(
            model_name='ritual',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='ritual',
            name='name_ka',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название (GE)'),
        ),
        migrations.AddField(
            model_name='ritual',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название (RU)'),
        ),
        migrations.AddField(
            model_name='ritual',
            name='tag_ka',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тег / Бейдж (GE)'),
        ),
        migrations.AddField(
            model_name='ritual',
            name='tag_ru',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тег / Бейдж (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='announcement_ticker',
            field=models.TextField(default='TOCHKA • YOUR SPACE TO BREATHE • WE PRESS PAUSE FOR YOU • 30% OFF YOUR 5TH MASSAGE • 46 LUKA ASATIANI ST, BATUMI', verbose_name='Бегущая строка (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='booking_btn_text',
            field=models.CharField(default='CONFIRM RESERVATION', max_length=50, verbose_name='Бронирование: Кнопка (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='booking_heading',
            field=models.CharField(default='RESERVE YOUR SANCTUARY', max_length=100, verbose_name='Бронирование: Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='booking_lead',
            field=models.TextField(default='Select your ritual and preferred time. Master Anna Kolosova will confirm your appointment within 15 minutes.', verbose_name='Бронирование: Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='btn_book_header_text',
            field=models.CharField(default='BOOK A SESSION', max_length=50, verbose_name='Кнопка в шапке (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_author',
            field=models.CharField(default='— Anna Kolosova • TOCHKA Founder & Therapist', max_length=100, verbose_name='01 Автор цитаты (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_card_1_text',
            field=models.TextField(default="Our signature continuous-contact technique: the therapist's hands barely leave the body, moving in a smooth meditative flow. This rhythm signals safety to the nervous system, releasing chronic tension without sudden changes in pace.", verbose_name='01 Карточка 1 Текст (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_card_1_title',
            field=models.CharField(default='Continuous-Contact Touch', max_length=100, verbose_name='01 Карточка 1 Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_card_2_text',
            field=models.TextField(default='Natural coconut oil or delicate cream, fresh soft white towels, personalized guest playlist instead of generic sounds, and a relaxed cup of coffee or herbal tea after your session.', verbose_name='01 Карточка 2 Текст (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_card_2_title',
            field=models.CharField(default='Atmosphere of Gentle Care', max_length=100, verbose_name='01 Карточка 2 Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_heading',
            field=models.CharField(default='CONCEPT & PHILOSOPHY', max_length=100, verbose_name='01 Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_quote',
            field=models.TextField(default='"TOCHKA sounds confident and clear here, like a deep breath and a slow exhale. The strictness of the lines creates a sense of stability and support — the foundation on which recovery is built."', verbose_name='01 Цитата (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_copyright',
            field=models.CharField(default='© 2023–2026 TOCHKA. Anna Kolosova Massage Sanctuary, Batumi.', max_length=150, verbose_name='Подвал: Копирайт'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_motto',
            field=models.TextField(default='Your space to breathe. Aesthetics & comfort as part of the healing process.', verbose_name='Подвал: Слоган (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_btn_text',
            field=models.CharField(default='PURCHASE GIFT CERTIFICATE', max_length=50, verbose_name='04 Кнопка (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_heading',
            field=models.CharField(default='GIFT CARDS & CERTIFICATES', max_length=100, verbose_name='04 Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_subtext',
            field=models.TextField(default='Give the gift of presence, tranquility, and restorative self-care.', verbose_name='04 Подзаголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_badge_tag',
            field=models.CharField(default='WELLNESS SANCTUARY', max_length=100, verbose_name='Hero: Бейдж (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_btn_book_text',
            field=models.CharField(default='BOOK APPOINTMENT', max_length=50, verbose_name='Hero: Кнопка 2 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_btn_explore_text',
            field=models.CharField(default='EXPLORE RITUALS', max_length=50, verbose_name='Hero: Кнопка 1 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_card_tag_title',
            field=models.CharField(default='TOCHKA RITUAL', max_length=100, verbose_name='Hero: Метка на фото (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(default='TOCHKA is born at the meeting point of body and soul — where touch becomes a language of care, and space itself breathes tranquility. It is a place where the noise of the city can be left behind, and one can hear themselves again.', verbose_name='Hero: Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_feat_1_num',
            field=models.CharField(default='01', max_length=10, verbose_name='Hero: Преимущество 1 Номер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_feat_1_text',
            field=models.CharField(default='Continuous-Contact Technique', max_length=100, verbose_name='Hero: Преимущество 1 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_feat_2_num',
            field=models.CharField(default='02', max_length=10, verbose_name='Hero: Преимущество 2 Номер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_feat_2_text',
            field=models.CharField(default='Natural Coconut Oil & Care', max_length=100, verbose_name='Hero: Преимущество 2 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_feat_3_num',
            field=models.CharField(default='03', max_length=10, verbose_name='Hero: Преимущество 3 Номер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_feat_3_text',
            field=models.CharField(default='10% Off 1st Visit • 30% Off 5th', max_length=100, verbose_name='Hero: Преимущество 3 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero: Главное изображение (справа)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_main_title',
            field=models.CharField(default='Your space to breathe.', max_length=200, verbose_name='Hero: Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loc_address',
            field=models.CharField(default='46 Luka Asatiani St, Batumi 6000, Georgia', max_length=150, verbose_name='Контакты: Адрес'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loc_email',
            field=models.EmailField(default='concierge@tochka.ge', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loc_gmaps_url',
            field=models.URLField(default='https://maps.app.goo.gl/xjAE2yyKdikHBroi9', verbose_name='Google Maps Ссылка'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loc_hours',
            field=models.CharField(default='Daily: 09:00 — 23:00', max_length=100, verbose_name='Контакты: Часы работы'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loc_instagram_url',
            field=models.URLField(default='https://www.instagram.com/toch._ka/', verbose_name='Instagram Ссылка'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loc_phone',
            field=models.CharField(default='+995 591 22 61 45', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loc_whatsapp_url',
            field=models.URLField(default='https://wa.me/message/vopznnayguwab1', verbose_name='WhatsApp Ссылка'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_desc',
            field=models.TextField(default='Receive more pleasure and care for yourself. Enjoy 30% off your 5th massage — our little ritual of gratitude. Collect 4 stamps and receive your privilege on the 5th session.', verbose_name='03 Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_heading',
            field=models.CharField(default='THE RITUAL OF GRATITUDE', max_length=100, verbose_name='03 Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='03 Изображение карты лояльности'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_subtitle',
            field=models.CharField(default='30% Privilege on Your 5th Massage', max_length=150, verbose_name='03 Подзаголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='manifesto_huge_text',
            field=models.CharField(default='ALL YOU KNEAD IS CARE', max_length=100, verbose_name='Манифест: Большой текст (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='manifesto_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Манифест: Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='manifesto_small_text',
            field=models.CharField(default='TOCHKA • 46 LUKA ASATIANI ST, BATUMI', max_length=100, verbose_name='Манифест: Нижняя подпись'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='palette_heading',
            field=models.CharField(default='COLOUR PALETTE & IDENTITY', max_length=100, verbose_name='Палитра: Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='palette_subtext',
            field=models.TextField(default='Iron metallic black, brushed titanium steel, platinum sand, and raw forged charcoal.', verbose_name='Палитра: Описание'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_badge',
            field=models.CharField(default='FIRST VISIT WELCOME', max_length=50, verbose_name='02 Промо: Бейдж (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_btn_text',
            field=models.CharField(default='CLAIM 10% DISCOUNT', max_length=50, verbose_name='02 Промо: Кнопка (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_subtitle',
            field=models.TextField(default='Experience our signature continuous-contact massage with master. Includes organic coconut oil and complimentary post-session tea or coffee.', verbose_name='02 Промо: Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_title',
            field=models.CharField(default='10% Privilege on Your First Session', max_length=150, verbose_name='02 Промо: Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reel_1_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Reel 1: Постер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reel_2_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Reel 2: Постер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reel_3_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Reel 3: Постер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reel_4_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Reel 4: Постер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reels_heading',
            field=models.CharField(default='ATMOSPHERE & INSTAGRAM REELS', max_length=100, verbose_name='05 Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='reels_subtext',
            field=models.CharField(default='Moments of deep breath, flowing oils and restorative touch at @toch._ka', max_length=200, verbose_name='05 Подзаголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='rituals_heading',
            field=models.CharField(default='THERAPIES & RITUALS', max_length=100, verbose_name='02 Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='rituals_subtext',
            field=models.TextField(default='Authentic treatments, precise myofascial techniques, and deep restorative care in Batumi.', verbose_name='02 Подзаголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='description',
            field=models.TextField(verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название (EN)'),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='price_1',
            field=models.CharField(default='$45', max_length=50, verbose_name='Стоимость 1 (USD / GEL)'),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='price_2',
            field=models.CharField(blank=True, default='$60', max_length=50, verbose_name='Стоимость 2 (USD / GEL)'),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='tag',
            field=models.CharField(blank=True, help_text='Popular, Signature Technique...', max_length=50, verbose_name='Тег / Бейдж (EN)'),
        ),
    ]
