# Generated by Django 6.1 on 2026-08-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_homepage_giftcards_picker_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='loc_telegram_url',
            field=models.URLField(default='https://t.me/tochka_batumi', verbose_name='Telegram Ссылка'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whatsapp_notify_apikey',
            field=models.CharField(blank=True, default='', help_text="Бесплатный API-ключ от CallMeBot (получите, отправив 'I allow callmebot to send me messages' на номер +34 911 06 73 98 в WhatsApp)", max_length=50, verbose_name='CallMeBot WhatsApp API Key'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whatsapp_notify_phone',
            field=models.CharField(blank=True, default='', help_text='Номер телефона мастера/администратора с кодом страны (например +995591226145), куда CallMeBot будет отправлять уведомления', max_length=30, verbose_name='WhatsApp для уведомлений о записях'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='announcement_ticker',
            field=models.TextField(default='TOCHKA • YOUR SPACE TO BREATHE • WE PRESS PAUSE FOR YOU • 20% OFF YOUR 5TH MASSAGE • 46 LUKA ASATIANI ST, BATUMI', verbose_name='Бегущая строка (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='announcement_ticker_ka',
            field=models.TextField(blank=True, default='წერტილი • თქვენი სივრცე სუნთქვისთვის • 20% ფასდაკლება მე-5 მასაჟზე • ბათუმი, ლუკა ასათიანის 46', verbose_name='Бегущая строка (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='announcement_ticker_ru',
            field=models.TextField(blank=True, default='ТОЧКА • ВАШЕ ПРОСТРАНСТВО ДЛЯ ДЫХАНИЯ • СКИДКА 20% НА 5-Й СЕАНС • БАТУМИ, УЛ. ЛУКИ АСАТИАНИ, 46', verbose_name='Бегущая строка (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_quote',
            field=models.TextField(default='“I wanted to create a place where you can feel tranquility from the very first moments: soft light, quiet, pleasant interior details, and a feeling of warmth. It is important to me that here you can not only relax your body, but also slow down, escape the everyday rush, and simply be in a comfortable, peaceful atmosphere.”', verbose_name='01 Цитата (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_quote_ka',
            field=models.TextField(blank=True, default='„მინდოდა შემექმნა ადგილი, სადაც პირველივე წუთებიდან იგრძნობთ სიმშვიდეს: რბილი სინათლე, სიჩუმე, ინტერიერის სასიამოვნო დეტალები და სიმყუდროვე. ჩემთვის მნიშვნელოვანია, რომ აქ შეძლოთ არა მხოლოდ სხეულის მოდუნება, არამედ ცოტათი შეჩერება, ყოველდღიური აურზაურისგან განტვირთვა და კომფორტულ, მშვიდ გარემოში ყოფნა“.', verbose_name='01 Цитата (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_quote_ru',
            field=models.TextField(blank=True, default='«Мне хотелось создать место, в котором можно почувствовать спокойствие уже с первых минут: мягкий свет, тишина, приятные детали интерьера и ощущение уюта. Для меня важно, чтобы здесь вы могли не только расслабить тело, но и немного замедлиться, отвлечься от суеты и побыть в комфортной, спокойной обстановке».', verbose_name='01 Цитата (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_feat_3_text',
            field=models.CharField(default='10% Off 1st Visit • 20% Off 5th', max_length=100, verbose_name='Hero: Преимущество 3 (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_feat_3_text_ka',
            field=models.CharField(blank=True, default='10% ფასდაკლება 1-ლ სეანსზე • 20% მე-5-ზე', max_length=100, verbose_name='Hero: Преимущество 3 (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_feat_3_text_ru',
            field=models.CharField(blank=True, default='Скидка 10% на 1-й сеанс • 20% на 5-й', max_length=100, verbose_name='Hero: Преимущество 3 (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_desc',
            field=models.TextField(default='Receive more pleasure and care for yourself. Enjoy 20% off your 5th massage — our little ritual of gratitude. Collect 4 stamps and receive your privilege on the 5th session.', verbose_name='03 Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_desc_ka',
            field=models.TextField(blank=True, default='მეტი სიამოვნება და ზრუნვა საკუთარ თავზე. 20%-იანი ფასდაკლება მე-5 მასაჟზე — ჩვენი მადლიერების რიტუალი.', verbose_name='03 Описание (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_desc_ru',
            field=models.TextField(blank=True, default='Больше удовольствия и заботы о себе. Скидка 20% на каждый 5-й массаж — наш маленький ритуал благодарности за ваше доверие. Соберите 4 отметки и получите скидку 20% на 5-й сеанс.', verbose_name='03 Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_subtitle',
            field=models.CharField(default='20% Privilege on Your 5th Massage', max_length=150, verbose_name='03 Подзаголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_subtitle_ka',
            field=models.CharField(blank=True, default='20% ფასდაკლება ყოველ მე-5 მასაჟზე', max_length=150, verbose_name='03 Подзаголовок (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_subtitle_ru',
            field=models.CharField(blank=True, default='Привилегия 20% на каждый 5-й массаж', max_length=150, verbose_name='03 Подзаголовок (RU)'),
        ),
    ]
