# Generated by Django 6.1 on 2026-08-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_loc_telegram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='loc_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
    ]
