# Generated by Django 6.1 on 2026-08-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_loc_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_btn_text',
            field=models.CharField(default='ORDER CERTIFICATE (OR IN PERSON)', max_length=100, verbose_name='04 Кнопка (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_btn_text_ka',
            field=models.CharField(blank=True, default='სერტიფიკატის შეძენა (ან პირადად)', max_length=100, verbose_name='04 Кнопка (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_btn_text_ru',
            field=models.CharField(blank=True, default='ОФОРМИТЬ СЕРТИФИКАТ (МОЖНО ЛИЧНО)', max_length=100, verbose_name='04 Кнопка (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_badge_tag_ka',
            field=models.CharField(blank=True, default='WELLNESS SANCTUARY', max_length=100, verbose_name='Hero: Бейдж (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_badge_tag_ru',
            field=models.CharField(blank=True, default='WELLNESS SANCTUARY', max_length=100, verbose_name='Hero: Бейдж (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(default='TOCHKA is born at the meeting point of body and soul — a space to slow down, release tension, and restore your inner calm in gentle care.', verbose_name='Hero: Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description_ka',
            field=models.TextField(blank=True, default='TOCHKA იბადება სხეულისა და სულის შეხვედრის ადგილზე — სივრცე, სადაც შეგიძლიათ შეანელოთ ტემპი, მოიხსნათ დაძაბულობა და აღიდგინოთ შინაგანი სიმშვიდე.', verbose_name='Hero: Описание (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description_ru',
            field=models.TextField(blank=True, default='ТОЧКА рождается на стыке тела и души — пространство, где можно замедлиться, отпустить напряжение и восстановить внутреннее спокойствие в бережной заботе.', verbose_name='Hero: Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_main_title',
            field=models.CharField(default='A space<br /><span class="italic-serif">where you can slow down</span>', max_length=200, verbose_name='Hero: Заголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_main_title_ka',
            field=models.CharField(blank=True, default='სივრცე,<br /><span class="italic-serif">სადაც შეგიძლიათ შენელდეთ</span>', max_length=200, verbose_name='Hero: Заголовок (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_main_title_ru',
            field=models.CharField(blank=True, default='Пространство,<br /><span class="italic-serif">где можно замедлиться</span>', max_length=200, verbose_name='Hero: Заголовок (RU)'),
        ),
    ]
