# Generated by Django on 2026-08-24
from django.db import migrations


def set_production_site(apps, schema_editor):
    Site = apps.get_model("wagtailcore", "Site")
    site = Site.objects.filter(is_default_site=True).first()
    if not site:
        site = Site.objects.first()
    if site:
        site.hostname = "tochkabatumi.ge"
        site.port = 443
        site.site_name = "TOCHKA — Your Space to Breathe"
        site.is_default_site = True
        site.save()


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_giftcards_btn_text_and_more"),
    ]

    operations = [
        migrations.RunPython(set_production_site, reverse_code=migrations.RunPython.noop),
    ]
