# Generated by Django 6.1 on 2026-08-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_update_loyalty_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_btn_text',
            field=models.CharField(default='PURCHASE IN SANCTUARY IN PERSON', max_length=100, verbose_name='04 Кнопка (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_btn_text_ka',
            field=models.CharField(blank=True, default='შეძენა სალონში პირადად', max_length=100, verbose_name='04 Кнопка (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_btn_text_ru',
            field=models.CharField(blank=True, default='ОФОРМИТЬ В САЛОНЕ ЛИЧНО', max_length=100, verbose_name='04 Кнопка (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_desc',
            field=models.TextField(default='Receive more pleasure and care for yourself. Enjoy 20% off your 5th massage — our little ritual of gratitude.', verbose_name='03 Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_desc_ru',
            field=models.TextField(blank=True, default='Больше удовольствия и заботы о себе. Скидка 20% на каждый 5-й массаж — наш маленький ритуал благодарности за ваше доверие.', verbose_name='03 Описание (RU)'),
        ),
    ]
