# Generated by Django 6.1 on 2026-08-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_giftcards_btn_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(default='Анна Колосова', max_length=100, verbose_name='Имя мастера')),
                ('master_role', models.CharField(default='Основатель и единственный ведущий мастер студии', max_length=150, verbose_name='Статус')),
                ('master_bio', models.TextField(blank=True, default='Все сеансы массажа в студии TOCHKA проводит лично основатель Анна Колосова по авторской технике непрерывного контакта. Других мастеров в студии нет, что гарантирует полную приватность и персональное внимание.', verbose_name='Информация о мастере')),
                ('master_phone', models.CharField(default='+995 591 226 145', max_length=50, verbose_name='Телефон мастера / WhatsApp')),
                ('ai_enabled', models.BooleanField(default=True, verbose_name='Включить ИИ-администратора')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Токен от @BotFather (если пусто — используется значение из .env)', max_length=200, verbose_name='Telegram Bot Token')),
                ('ai_custom_instructions', models.TextField(blank=True, help_text='Особые указания или актуальные новости для ответов гостям', verbose_name='Дополнительные инструкции для ИИ')),
                ('whatsapp_provider', models.CharField(choices=[('greenapi', 'Green API (QR-код)'), ('meta', 'Meta WhatsApp Cloud API')], default='greenapi', max_length=20, verbose_name='Провайдер WhatsApp')),
                ('whatsapp_greenapi_instance', models.CharField(blank=True, max_length=100, verbose_name='Green API Instance ID')),
                ('whatsapp_greenapi_token', models.CharField(blank=True, max_length=150, verbose_name='Green API Token')),
                ('first_visit_discount', models.CharField(default='10%', max_length=50, verbose_name='Скидка на первый визит')),
                ('first_visit_code', models.CharField(default='FIRST10', max_length=50, verbose_name='Промокод на первый визит')),
            ],
            options={
                'verbose_name': 'Настройки ИИ и Мастера',
                'verbose_name_plural': 'Настройки ИИ и Мастера',
            },
        ),
        migrations.AlterField(
            model_name='homepage',
            name='booking_lead',
            field=models.TextField(default='Select your ritual and preferred time. Master Anna will confirm your appointment within 15 minutes', verbose_name='Бронирование: Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='booking_lead_ka',
            field=models.TextField(blank=True, default='აირჩიეთ სასურველი რიტუალი და დრო. მასტერი ანა დაადასტურებს თქვენს ჯავშანს 15 წუთში', verbose_name='Бронирование: Описание (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='booking_lead_ru',
            field=models.TextField(blank=True, default='Выберите желаемый ритуал и удобное время. Мастер Анна подтвердит вашу бронь в течение 15 минут', verbose_name='Бронирование: Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='01 Автор цитаты (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_author_ka',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='01 Автор цитаты (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_author_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='01 Автор цитаты (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_card_1_text_ka',
            field=models.TextField(blank=True, default='საავტორო უწყვეტი კონტაქტის ტექნიკა: თერაპევტის ხელები პრაქტიკულად არ შორდება სხეულს, მოძრაობს მდორე მედიტაციურ ნაკადში', verbose_name='01 Карточка 1 Текст (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_card_1_text_ru',
            field=models.TextField(blank=True, default='Авторская техника непрерывного контакта: руки мастера практически не отрываются от тела, переходя из одного движения в другое. Такой ритм дает нервной системе сигнал безопасности и глубоко снимает накопившийся стресс', verbose_name='01 Карточка 1 Текст (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_card_2_text',
            field=models.TextField(default='Natural coconut oil or delicate cream, fresh soft white towels, personalized guest playlist instead of generic sounds, and a relaxed cup of coffee or herbal tea after your session', verbose_name='01 Карточка 2 Текст (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_card_2_text_ka',
            field=models.TextField(blank=True, default='ნატურალური ქოქოსის ზეთი, რბილი პირსახოცები, პერსონალური მუსიკა და ყავა ან ჩაი სეანსის შემდეგ', verbose_name='01 Карточка 2 Текст (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_card_2_text_ru',
            field=models.TextField(blank=True, default='Натуральное кокосовое масло или нежный питательный крем, белоснежные полотенца, персональный плейлист гостя вместо шаблонных звуков и чашка чая или кофе после сеанса', verbose_name='01 Карточка 2 Текст (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_quote',
            field=models.TextField(default='“I wanted to create a place where you can feel tranquility from the very first moments: soft light, quiet, pleasant interior details, and a feeling of warmth. It is important to me that here you can not only relax your body, but also slow down, escape the everyday rush, and simply be in a comfortable, peaceful atmosphere”', verbose_name='01 Цитата (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_quote_ka',
            field=models.TextField(blank=True, default='„მინდოდა შემექმნა ადგილი, სადაც პირველივე წუთებიდან იგრძნობთ სიმშვიდეს: რბილი სინათლე, სიჩუმე, ინტერიერის სასიამოვნო დეტალები და სიმყუდროვე. ჩემთვის მნიშვნელოვანია, რომ აქ შეძლოთ არა მხოლოდ სხეულის მოდუნება, არამედ ცოტათი შეჩერება, ყოველდღიური აურზაურისგან განტვირთვა და კომფორტულ, მშვიდ გარემოში ყოფნა“', verbose_name='01 Цитата (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='concept_quote_ru',
            field=models.TextField(blank=True, default='«Мне хотелось создать место, в котором можно почувствовать спокойствие уже с первых минут: мягкий свет, тишина, приятные детали интерьера и ощущение уюта. Для меня важно, чтобы здесь вы могли не только расслабить тело, но и немного замедлиться, отвлечься от суеты и побыть в комфортной, спокойной обстановке»', verbose_name='01 Цитата (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_copyright',
            field=models.CharField(default='© 2023–2026 TOCHKA. Anna Kolosova Massage Sanctuary, Batumi', max_length=150, verbose_name='Подвал: Копирайт'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_motto',
            field=models.TextField(default='Your space to breathe. Aesthetics & comfort as part of the healing process', verbose_name='Подвал: Слоган (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_motto_ka',
            field=models.TextField(blank=True, default='თქვენი სივრცე სუნთქვისთვის. ესთეტიკა და კომფორტი, როგორც განკურნების ნაწილი', verbose_name='Подвал: Слоган (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_motto_ru',
            field=models.TextField(blank=True, default='Ваше пространство для дыхания. Эстетика и забота как часть процесса восстановления', verbose_name='Подвал: Слоган (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_subtext',
            field=models.TextField(default='Give the gift of presence, tranquility, and restorative self-care', verbose_name='04 Подзаголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_subtext_ka',
            field=models.TextField(blank=True, default='აჩუქეთ სიმშვიდის, დასვენებისა და ზრუნვის დაუვიწყარი წუთები', verbose_name='04 Подзаголовок (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='giftcards_subtext_ru',
            field=models.TextField(blank=True, default='Подарите близким моменты спокойствия, тишины и бережного восстановления', verbose_name='04 Подзаголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_card_tag_title',
            field=models.CharField(default='TOCHKA', max_length=100, verbose_name='Hero: Метка на фото (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_card_tag_title_ka',
            field=models.CharField(blank=True, default='TOCHKA', max_length=100, verbose_name='Hero: Метка на фото (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_card_tag_title_ru',
            field=models.CharField(blank=True, default='ТОЧКА', max_length=100, verbose_name='Hero: Метка на фото (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(default='TOCHKA is born at the meeting point of body and soul — a space to slow down, release tension, and restore your inner calm in gentle care', verbose_name='Hero: Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description_ka',
            field=models.TextField(blank=True, default='TOCHKA იბადება სხეულისა და სულის შეხვედრის ადგილზე — სივრცე, სადაც შეგიძლიათ შეანელოთ ტემპი, მოიხსნათ დაძაბულობა და აღიდგინოთ შინაგანი სიმშვიდე', verbose_name='Hero: Описание (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_description_ru',
            field=models.TextField(blank=True, default='ТОЧКА рождается на стыке тела и души — пространство, где можно замедлиться, отпустить напряжение и восстановить внутреннее спокойствие в бережной заботе', verbose_name='Hero: Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_desc',
            field=models.TextField(default='Receive more pleasure and care for yourself. Enjoy 20% off your 5th massage — my little ritual of gratitude', verbose_name='03 Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_desc_ka',
            field=models.TextField(blank=True, default='მეტი სიამოვნება და ზრუნვა საკუთარ თავზე. 20%-იანი ფასდაკლება მე-5 მასაჟზე — ჩემი მადლიერების რიტუალი', verbose_name='03 Описание (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='loyalty_desc_ru',
            field=models.TextField(blank=True, default='Больше удовольствия и заботы о себе. Скидка 20% на каждый 5-й массаж — мой маленький ритуал благодарности за ваше доверие', verbose_name='03 Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='palette_subtext',
            field=models.TextField(default='Iron metallic black, brushed titanium steel, platinum sand, and raw forged charcoal', verbose_name='Палитра: Описание'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_subtitle',
            field=models.TextField(default='Experience our signature continuous-contact massage with master. Includes organic coconut oil and complimentary post-session tea or coffee', verbose_name='02 Промо: Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_subtitle_ka',
            field=models.TextField(blank=True, default='გაეცანით ჩვენს საავტორო უწყვეტი კონტაქტის მასაჟს. მოიცავს ორგანულ ქოქოსის ზეთს და ჩაის/ყავას სეანსის შემდეგ', verbose_name='02 Промо: Описание (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_subtitle_ru',
            field=models.TextField(blank=True, default='Познакомьтесь с авторской техникой непрерывного контакта и ощутите глубокое расслабление. Натуральные масла и чай/кофе включены', verbose_name='02 Промо: Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='rituals_subtext',
            field=models.TextField(default='Authentic treatments, precise myofascial techniques, and deep restorative care in Batumi', verbose_name='02 Подзаголовок (EN)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='rituals_subtext_ka',
            field=models.TextField(blank=True, default='ავთენტური პროცედურები, ზუსტი მიოფასციალური ტექნიკა და ღრმა აღდგენითი ზრუნვა ბათუმში', verbose_name='02 Подзаголовок (GE)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='rituals_subtext_ru',
            field=models.TextField(blank=True, default='Проверенные методики, прицельная проработка триггерных зон и холистический уход в Батуми', verbose_name='02 Подзаголовок (RU)'),
        ),
    ]
