# Generated by Django 6.1 on 2026-08-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_aisettings_ai_model_name_aisettings_ai_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='telegram_admin_usernames',
            field=models.CharField(default='Kingmachineflayer, Ankolosova', help_text='Список username администраторов через запятую (например: Kingmachineflayer, Ankolosova). Этим пользователям бот предоставляет права управления заявками, расписанием и подтверждением броней.', max_length=255, verbose_name='Telegram Администраторы'),
        ),
    ]
