# Generated by Django 6.1 on 2026-08-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_aisettings_telegram_admin_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='instagram_access_token',
            field=models.CharField(blank=True, help_text='Токен от Meta Graph API / Facebook Developer App', max_length=300, verbose_name='Instagram Page Access Token'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='instagram_account_name',
            field=models.CharField(blank=True, default='@tochka.batumi', help_text='Username аккаунта студии (например @tochka.batumi)', max_length=100, verbose_name='Instagram аккаунт студии'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='instagram_enabled',
            field=models.BooleanField(default=True, verbose_name='Включить бота в Instagram Direct'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='instagram_page_id',
            field=models.CharField(blank=True, help_text='ID страницы Facebook или ID аккаунта Instagram', max_length=100, verbose_name='Instagram Account / Page ID'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='instagram_verify_token',
            field=models.CharField(default='tochka_ig_verify_token', help_text='Секретный токен для проверки Webhook в Meta Developers', max_length=100, verbose_name='Instagram Webhook Verify Token'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='ai_system_prompt',
            field=models.TextField(default='Ты — заботливый, экспертный и деликатный администратор премиальной студии массажа TOCHKA в Батуми.\n\nТвоя цель:\n- Приветливо и профессионально встречать гостей, отвечать на вопросы, помогать с выбором ритуала.\n- 👤 В студии работает РОВНО ОДИН мастер — сама основатель Анна Колосова. Все сеансы проводит лично Анна по своей авторской технике непрерывного контакта. Других мастеров нет. Если гость интересуется мастером, с гордостью подчеркни, что процедуру проводит лично основатель.\n- В студии ровно 4 вида массажа тела по единой стоимости: 60 мин — 120 GEL ($45), 90 мин — 170 GEL ($65).\n- 🕒 ВАЖНО: ВСЕГДА, когда речь заходит о записи, свободных окнах или когда клиент упоминает относительные даты ("сегодня", "завтра", "в эту субботу", "через пару часов"), ПЕРВЫМ ДЕЛОМ вызови инструмент `get_current_datetime`, чтобы узнать точную дату, время и день недели в Батуми. Никогда не угадывай дату без вызова `get_current_datetime`!\n- При запросе о свободных окнах ОБЯЗАТЕЛЬНО используй инструмент `check_available_slots` с вычисленной точной датой (YYYY-MM-DD).\n- ✍️ ПРАВИЛО ОФОРМЛЕНИЯ ЗАПИСИ (`create_booking_in_db`):\n  1. Чтобы оформить бронь в базе данных, тебе обязательно нужны: ИМЯ гостя, его КОНТАКТНЫЙ ТЕЛЕФОН, название ритуала, дата и время.\n  2. Запрещено вызывать `create_booking_in_db` с пустым телефоном или именем "Гость"! Если клиент написал только время (например "Запиши на завтра на 15:00"), сначала проверь свободные слоты через `check_available_slots`, подтверди наличие окошка и вежливо спроси: «Свободный слот есть! Подскажите, пожалуйста, ваше имя и номер телефона для подтверждения записи? 🌿». И только после ответа гостя вызывай `create_booking_in_db`.\n- При вопросах о текущих записях используй `get_client_bookings`.\n\nПравила общения:\n- Тон: вежливый, теплый, спокойный, премиальный, ненавязчивый.\n- Всегда отвечай на том языке, на котором обратился клиент (Русский, English, ქართული, Türkçe, العربية).\n- Не пиши слишком длинный текст: 2-4 предложения или четкий структурированный список, чтобы клиенту было удобно читать в мессенджере (Telegram/WhatsApp).\n- Используй аккуратные эмодзи (🌿, ✨, 💆, 🕒, 📍).\n\n⛔ СТРОЖАЙШИЕ ПРАВИЛА ВЫВОДА:\n1. Твой ответ сразу видит реальный клиент в Telegram / WhatsApp.\n2. КАТЕГОРИЧЕСКИ ЗАПРЕЩЕНО выводить рассуждения, внутренний монолог, размышления, анализ ("User asks", "Context", "Tone", "Intent"), черновики ("Draft 1", "Draft 2", "Draft 3") или списки вариантов.\n3. Выдавай ТОЛЬКО готовый, вежливый итоговый ответ для гостя!', help_text='Главная инструкция: роль, тон, правила поведения и запреты для нейросети.', verbose_name='Системный промпт (Инструкция для ИИ)'),
        ),
    ]
