# Generated by Django 6.1 on 2026-08-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('service_name', models.CharField(blank=True, max_length=150, verbose_name='Название услуги')),
                ('booking_date', models.DateField(verbose_name='Дата визита')),
                ('booking_time', models.CharField(default='12:00', max_length=20, verbose_name='Время визита')),
                ('notes', models.TextField(blank=True, verbose_name='Пожелания / Комментарий')),
                ('status', models.CharField(choices=[('pending', '⏳ Ожидает подтверждения'), ('confirmed', '✅ Подтверждена'), ('completed', '✨ Завершена'), ('cancelled', '❌ Отменена')], default='pending', max_length=20, verbose_name='Статус записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Онлайн-запись',
                'verbose_name_plural': 'Онлайн-записи',
                'ordering': ['-booking_date', '-created_at'],
            },
        ),
    ]
