# Generated by Django 6.1 on 2026-08-22 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('home', '0003_remove_homepage_giftcards_picker_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата запланированного сеанса', verbose_name='Дата визита'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(default='12:00', help_text='Время сеанса, например: 12:00, 14:30, 18:00', max_length=20, verbose_name='Время визита'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(blank=True, help_text='Электронная почта (необязательно)', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.CharField(help_text='ФИО или имя гостя', max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(help_text='Контактный номер для связи / WhatsApp', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительные пожелания гостя или примечания администратора', verbose_name='Пожелания / Комментарий'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Выберите услугу из каталога (если применимо)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='home.ritual', verbose_name='Ритуал / Процедура'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_name',
            field=models.CharField(blank=True, help_text='Заполняется автоматически при выборе услуги или вручную', max_length=150, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Ожидает подтверждения'), ('confirmed', '✅ Подтверждена'), ('completed', '✨ Завершена'), ('cancelled', '❌ Отменена')], default='pending', help_text='Текущее состояние бронирования', max_length=20, verbose_name='Статус записи'),
        ),
    ]
