# Generated by Django 6.1 on 2026-08-22 23:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Дата, для которой блокируется слот', verbose_name='Дата')),
                ('time_slot', models.CharField(choices=[('ALL_DAY', '⛔ Весь день (Выходной / Закрыто)'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], default='ALL_DAY', help_text="Выберите конкретный час или 'Весь день'", max_length=50, verbose_name='Время или период')),
                ('reason', models.CharField(blank=True, default='Занято / Недоступно', help_text='Например: Обед, Личная встреча, Выходной', max_length=200, verbose_name='Причина / Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заблокированный слот / Выходной',
                'verbose_name_plural': 'Заблокированные слоты / Выходные',
                'ordering': ['-date', 'time_slot'],
            },
        ),
    ]
