# Generated by Django 6.1 on 2026-09-13 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_blockedtimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedtimeslot',
            name='end_date',
            field=models.DateField(blank=True, help_text='Укажите, если хотите закрыть сразу несколько дней подряд (например, отпуск с 13 по 28 сентября). Все дни диапазона будут автоматически заблокированы!', null=True, verbose_name='Дата окончания (необязательно)'),
        ),
        migrations.AlterField(
            model_name='blockedtimeslot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата блокировки, либо дата начала периода (если нужно закрыть несколько дней подряд)', verbose_name='Дата начала (или один день)'),
        ),
        migrations.AlterField(
            model_name='blockedtimeslot',
            name='reason',
            field=models.CharField(blank=True, default='Выходной / Отпуск', help_text='Например: Отпуск мастера, Личные дела, Ремонт', max_length=200, verbose_name='Причина / Заметка'),
        ),
        migrations.AlterField(
            model_name='blockedtimeslot',
            name='time_slot',
            field=models.CharField(choices=[('ALL_DAY', '⛔ Весь день (Выходной / Закрыто)'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], default='ALL_DAY', help_text="Выберите конкретный час или 'Весь день' для выходного", max_length=50, verbose_name='Время или период'),
        ),
    ]
